# Generated by Django 5.1.6 on 2025-03-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_order_paymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225, verbose_name='Покупатель')),
                ('product', models.CharField(max_length=225, verbose_name='Продукт')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('check_image', models.ImageField(upload_to='media/check', verbose_name='Чек')),
                ('total_price', models.PositiveIntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'verbose_name': 'Заявка на оплату', 'verbose_name_plural': 'Заявки на оплату'},
        ),
        migrations.AlterModelOptions(
            name='ratinganswer',
            options={'verbose_name': 'Ответ на отзыв', 'verbose_name_plural': 'Ответы на отзывы'},
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='ratinganswer',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='ratinganswer',
            old_name='update_data',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_images',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='total_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, help_text='Фото которое будет отобрадажаться на обложке объявления', upload_to='media/main_covers', verbose_name='Главное фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Приянто'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='time_limit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ограничение по вермени'),
        ),
    ]
